//! End-to-end tests against `testdata/tlnet`, a tiny signed repository
//! generated by `tools/make_test_repo.sh` (packages `foo` → depends on
//! `bar`, and `fonts-x`). They run offline.

use std::fs;
use std::path::PathBuf;

use crate::ctx::{Ctx, Freshness};
use crate::db::now_secs;
use crate::ensure;
use crate::install;
use crate::db::Reason;
use crate::repo::ChecksumMismatch;
use crate::root::Root;

const KEY: &str = include_str!("../testdata/test-key.asc");
const FPR: &str = include_str!("../testdata/test-key.fpr");

fn testdata_repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/tlnet")
}

/// A fresh root using `repo` as its repository, with the test key trusted.
fn setup(repo: &std::path::Path) -> (tempfile::TempDir, Root, Ctx) {
    let dir = tempfile::tempdir().unwrap();
    let root = Root::new(dir.path().join("root"));
    let mut ctx = Ctx::open(root.clone()).unwrap();
    ctx.set_quiet(true);
    ctx.test_key = Some((KEY, FPR));
    ctx.db.set("repository", &format!("file://{}", repo.display())).unwrap();
    (dir, root, ctx)
}

#[test]
fn refresh_then_ensure_path_installs_with_siblings() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    assert!(matches!(ctx.refresh(true).unwrap(), Freshness::Updated { to: 4242, .. }));
    assert_eq!(ctx.refresh(false).unwrap(), Freshness::Fresh);
    drop(ctx);

    let got = ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", true).unwrap().unwrap();
    let rel: Vec<String> =
        got.iter().map(|p| p.strip_prefix(&root.dir).unwrap().to_string_lossy().into_owned()).collect();
    assert_eq!(rel[0], "texmf-dist/tex/latex/foo/foo.sty");
    // Siblings: the rest of foo, and bar, installed as foo's dependency.
    assert!(rel.contains(&"texmf-dist/tex/latex/foo/foo.lua".to_string()));
    assert!(rel.contains(&"texmf-dist/tex/latex/bar/bar.sty".to_string()));
    assert!(got.iter().all(|p| p.exists()));

    let ctx = Ctx::open(root.clone()).unwrap();
    let installed = ctx.db.installed().unwrap();
    assert_eq!(installed["foo"].reason, "auto");
    assert_eq!(installed["bar"].reason, "dependency");
    assert!(!installed.contains_key("fonts-x"));
    // The first install creates ls-R by a full (sorted) scan.
    let lsr = fs::read_to_string(root.texmf_dist().join("ls-R")).unwrap();
    assert!(lsr.contains("./tex/latex/foo:\nfoo.lua\nfoo.sty\n"), "{lsr}");
    assert!(lsr.contains("./tex/latex/bar:\nbar.sty\n"));

    // Already installed: just the path, nothing else.
    let again = ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", true).unwrap().unwrap();
    assert_eq!(again.len(), 1);
    // Paths outside texmf-dist or escaping it are refused.
    assert!(ensure::ensure_path(&root, "foo", "../etc/passwd", true).unwrap().is_none());
    assert!(ensure::ensure_path(&root, "foo", "bin/universal-darwin/x", true).unwrap().is_none());
}

#[test]
fn phase0_ensure_resolves_by_name() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    drop(ctx);
    let tfm = ensure::kind("tfm").unwrap();
    let p = ensure::ensure(&root, tfm, "x10").unwrap().unwrap();
    assert!(p.ends_with("texmf-dist/fonts/tfm/public/x/x10.tfm"));
    assert!(ensure::ensure(&root, ensure::kind("tex").unwrap(), "nonexistent.cfg").unwrap().is_none());
}

#[test]
fn unreachable_pinned_mirror_fails_over() {
    let (_d, _root, mut ctx) = setup(&testdata_repo());
    let configured = ctx.repository_url().unwrap();
    // Pin a mirror that refuses connections, as if resolved earlier.
    ctx.db.set("mirror", "http://127.0.0.1:9/tlnet/").unwrap();
    ctx.db.set("mirror_for", &configured).unwrap();
    ctx.db.set("mirror_pinned_at", &now_secs().to_string()).unwrap();

    assert!(matches!(ctx.refresh(true).unwrap(), Freshness::Updated { .. }));
    assert!(ctx.db.get("bad_mirror:127.0.0.1:9").unwrap().is_some());
    assert_eq!(ctx.db.get("mirror").unwrap().as_deref(), Some(format!("{configured}/").as_str()));
    assert!(!ctx.offline().unwrap());
}

#[test]
fn corrupt_archive_is_rejected() {
    let src = testdata_repo();
    let copy = tempfile::tempdir().unwrap();
    for sub in ["tlpkg", "archive"] {
        fs::create_dir_all(copy.path().join(sub)).unwrap();
        for e in fs::read_dir(src.join(sub)).unwrap() {
            let e = e.unwrap();
            fs::copy(e.path(), copy.path().join(sub).join(e.file_name())).unwrap();
        }
    }
    let mut bar = fs::read(copy.path().join("archive/bar.tar.xz")).unwrap();
    bar.push(0); // four bytes was enough to break a real mirror; one will do
    fs::write(copy.path().join("archive/bar.tar.xz"), bar).unwrap();

    let (_d, _root, mut ctx) = setup(copy.path());
    ctx.refresh(true).unwrap();
    let err = install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap_err();
    assert!(err.chain().any(|c| c.downcast_ref::<ChecksumMismatch>().is_some()), "{err:#}");
    assert!(ctx.db.installed().unwrap().is_empty(), "nothing may be installed after a failed download");
}

#[test]
fn interrupted_install_is_redone() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    assert!(!root.journal_dir().join("foo").exists());

    // As if mtx was killed while (re)installing bar.
    fs::write(root.journal_dir().join("bar"), b"").unwrap();
    fs::remove_file(root.texmf_dist().join("tex/latex/bar/bar.sty")).unwrap();
    let r = install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    assert_eq!(r.installed.iter().map(|(n, _)| n.as_str()).collect::<Vec<_>>(), vec!["bar"]);
    assert!(root.texmf_dist().join("tex/latex/bar/bar.sty").exists());
    assert!(!root.journal_dir().join("bar").exists());
    assert_eq!(ctx.db.installed().unwrap()["bar"].reason, "dependency");
}

#[test]
fn any_install_or_lookup_finishes_an_interrupted_install() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();

    // Killed while finishing foo (recorded, but ls-R/configuration not done):
    // installing something unrelated finishes it and keeps its reason.
    fs::write(root.journal_dir().join("foo"), b"").unwrap();
    let r = install::install(&mut ctx, &["fonts-x"], Reason::Auto).unwrap();
    let names: Vec<&str> = r.installed.iter().map(|(n, _)| n.as_str()).collect();
    assert!(names.contains(&"foo") && names.contains(&"fonts-x"), "{names:?}");
    assert!(!root.journal_dir().join("foo").exists());
    assert_eq!(ctx.db.installed().unwrap()["foo"].reason, "explicit");
    drop(ctx);

    // A lookup of a file that exists, but whose package is journaled,
    // redoes the package instead of trusting it; a healthy package's file
    // is returned at once.
    fs::write(root.journal_dir().join("bar"), b"").unwrap();
    let got = ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", false).unwrap().unwrap();
    assert!(got[0].exists());
    assert!(root.journal_dir().join("bar").exists(), "foo is healthy: no install");
    let got = ensure::ensure_path(&root, "bar", "texmf-dist/tex/latex/bar/bar.sty", false).unwrap().unwrap();
    assert!(got[0].exists());
    assert!(!root.journal_dir().join("bar").exists());
}

#[test]
fn remove_respects_dependencies() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    let err = install::remove(&mut ctx, &["bar"], false).unwrap_err();
    assert!(err.to_string().contains("foo depends on bar"), "{err:#}");

    assert_eq!(install::remove(&mut ctx, &["foo"], false).unwrap(), vec!["foo"]);
    assert!(!root.texmf_dist().join("tex/latex/foo").exists(), "empty directories are removed");
    assert!(root.texmf_dist().join("tex/latex/bar/bar.sty").exists());
    let lsr = fs::read_to_string(root.texmf_dist().join("ls-R")).unwrap();
    assert!(!lsr.contains("foo.sty") && lsr.contains("bar.sty"));
    assert_eq!(install::remove(&mut ctx, &["bar"], false).unwrap(), vec!["bar"]);
    assert!(ctx.db.installed().unwrap().is_empty());
}

fn testdata(sub: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata").join(sub)
}

#[test]
fn next_release_pins_the_frozen_repository() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();

    // tlnet moves on to TeX Live 2027. The first historic mirror is down.
    ctx.db.set("repository", &format!("file://{}", testdata("tlnet-next").display())).unwrap();
    ctx.unpin_mirror().unwrap();
    let historic = format!("file://{}", testdata("historic").display());
    ctx.db.set("historic_mirrors", &format!("http://127.0.0.1:9/ {historic}")).unwrap();

    assert!(matches!(ctx.refresh(true).unwrap(), Freshness::Updated { from: Some(4242), to: 4300 }));
    assert_eq!(ctx.db.get("repository").unwrap().as_deref(), Some("historic:2026"));
    assert_eq!(ctx.db.get_u64("newer_release").unwrap(), Some(2027));
    let mirror = ctx.db.get("mirror").unwrap().unwrap();
    assert_eq!(mirror, format!("{historic}/systems/texlive/2026/tlnet-final/"));
    assert!(ctx.tlpdb().unwrap().config.frozen);

    // Installs keep working from the frozen repository, and it stays pinned.
    install::install(&mut ctx, &["fonts-x"], Reason::Explicit).unwrap();
    assert!(root.texmf_dist().join("fonts/tfm/public/x/x10.tfm").exists());
    assert_eq!(ctx.refresh(true).unwrap(), Freshness::Unchanged);
}

#[test]
fn bootstrap_from_carries_requested_and_on_demand_packages() {
    let (_d, old_root, mut old) = setup(&testdata_repo());
    old.refresh(true).unwrap();
    install::install(&mut old, &["foo"], Reason::Explicit).unwrap();
    install::install(&mut old, &["fonts-x"], Reason::Auto).unwrap();
    old.db.record("dropped-in-2027", 1, Reason::Explicit, &[]).unwrap();
    drop(old);

    let (_d2, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    let c = crate::bootstrap::carried_packages(&ctx.tlpdb().unwrap(), &old_root).unwrap();
    // bar came in as foo's dependency; foo brings it again.
    assert_eq!(c.explicit, vec!["foo"]);
    assert_eq!(c.auto, vec!["fonts-x"]);
    assert_eq!(c.unknown, vec!["dropped-in-2027"]);
    let empty = Root::new(root.dir.join("nothing-here"));
    assert!(crate::bootstrap::carried_packages(&ctx.tlpdb().unwrap(), &empty).is_err());
}

mod consent_tests {
    use std::sync::atomic::{AtomicUsize, Ordering};

    use super::*;
    use crate::consent::{Answer, Declined};

    fn auto_install(ctx: &mut Ctx, pkg: &str) -> anyhow::Result<install::Report> {
        ctx.ask_for = Some(format!("{pkg}.sty"));
        install::install(ctx, &[pkg], Reason::Auto)
    }

    #[test]
    fn autoinstall_no_declines_and_logs() {
        let (_d, root, mut ctx) = setup(&testdata_repo());
        ctx.refresh(true).unwrap();
        ctx.db.set("autoinstall", "no").unwrap();
        drop(ctx);
        assert!(ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", false).unwrap().is_none());
        assert!(!root.texmf_dist().join("tex/latex/foo/foo.sty").exists());
        let problems: Vec<_> = crate::logview::tail(&root).into_iter().filter(|e| e.is_problem()).collect();
        assert_eq!(problems.len(), 1);
        assert!(problems[0].msg.starts_with("declined: foo.sty needs package foo and 1 more"), "{}", problems[0].msg);
        // Explicit installs are not subject to the policy.
        let mut ctx = Ctx::open(root.clone()).unwrap();
        ctx.set_quiet(true);
        ctx.test_key = Some((KEY, FPR));
        install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    }

    #[test]
    fn ask_without_any_ui_uses_the_fallback() {
        let (_d, root, mut ctx) = setup(&testdata_repo());
        ctx.refresh(true).unwrap();
        ctx.db.set("autoinstall", "ask").unwrap();
        ctx.prompter = |_, _| Err("no terminal; dialog: osascript exit 1".into());
        auto_install(&mut ctx, "bar").unwrap(); // fallback defaults to yes
        // The log says why nobody was asked and where the request came from.
        let log = fs::read_to_string(root.log_path()).unwrap();
        let line = log.lines().find(|l| l.contains("could not ask about")).expect(&log);
        assert!(line.contains("(no terminal; dialog: osascript exit 1; from "), "{line}");
        assert!(line.ends_with("ask_fallback is yes"), "{line}");
        ctx.db.set("ask_fallback", "no").unwrap();
        let err = auto_install(&mut ctx, "fonts-x").unwrap_err();
        assert!(err.downcast_ref::<Declined>().is_some(), "{err:#}");
        assert!(!ctx.db.installed().unwrap().contains_key("fonts-x"));
    }

    static ASKED: AtomicUsize = AtomicUsize::new(0);

    #[test]
    fn ask_all_covers_the_rest_of_the_run() {
        let (_d, _root, mut ctx) = setup(&testdata_repo());
        ctx.refresh(true).unwrap();
        ctx.db.set("autoinstall", "ask").unwrap();
        ctx.prompter = |_, q| {
            assert!(q.starts_with("foo.sty needs package foo and 1 more"), "{q}");
            ASKED.fetch_add(1, Ordering::SeqCst);
            Ok((Answer::All, "test"))
        };
        auto_install(&mut ctx, "foo").unwrap();
        auto_install(&mut ctx, "fonts-x").unwrap(); // not asked again
        assert_eq!(ASKED.load(Ordering::SeqCst), 1);
        let installed = ctx.db.installed().unwrap();
        assert_eq!(installed["foo"].reason, "auto");
        assert!(installed.contains_key("fonts-x"));
    }

    #[test]
    fn ask_none_declines_the_rest_of_the_run() {
        let (_d, _root, mut ctx) = setup(&testdata_repo());
        ctx.refresh(true).unwrap();
        ctx.db.set("autoinstall", "ask").unwrap();
        ctx.prompter = |_, _| Ok((Answer::None, "test"));
        assert!(auto_install(&mut ctx, "foo").is_err());
        ctx.prompter = |_, _| panic!("asked again after `none`");
        assert!(auto_install(&mut ctx, "fonts-x").is_err());
        assert!(ctx.db.installed().unwrap().is_empty());
    }
}

#[test]
fn documentation_is_installed_on_request_and_removed_with_its_package() {
    use crate::docs;
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    let manual = root.texmf_dist().join("doc/latex/foo/foo-manual.pdf");
    assert!(!manual.exists(), "runtime installs never bring documentation");

    let tlpdb = ctx.tlpdb().unwrap();
    assert_eq!(docs::packages_for(&tlpdb, "foo"), vec!["foo"]);
    assert_eq!(docs::packages_for(&tlpdb, "foo-manual"), vec!["foo"]); // by doc file name
    assert!(docs::packages_for(&tlpdb, "bar").is_empty()); // bar has no documentation

    assert_eq!(docs::install(&mut ctx, &["foo"], Reason::Auto).unwrap(), vec!["foo"]);
    assert!(manual.exists());
    assert_eq!(ctx.db.installed().unwrap()["foo.doc"].reason, "auto");
    let lsr = fs::read_to_string(root.texmf_dist().join("ls-R")).unwrap();
    assert!(lsr.contains("foo-manual.pdf"), "{lsr}");
    assert!(docs::install(&mut ctx, &["foo"], Reason::Auto).unwrap().is_empty());
    assert!(install::outdated(&ctx, &tlpdb).unwrap().is_empty());
    assert!(docs::install(&mut ctx, &["bar"], Reason::Auto).unwrap().is_empty());

    assert_eq!(install::remove(&mut ctx, &["foo"], false).unwrap(), vec!["foo", "foo.doc"]);
    assert!(!manual.exists());
}
