//! End-to-end tests against `testdata/tlnet`, a tiny signed repository
//! generated by `tools/make_test_repo.sh` (packages `foo` → depends on
//! `bar`, and `fonts-x`). They run offline.

use std::fs;
use std::path::PathBuf;

use crate::ctx::{Ctx, Freshness};
use crate::db::now_secs;
use crate::ensure;
use crate::install;
use crate::db::Reason;
use crate::repo::ChecksumMismatch;
use crate::root::Root;

const KEY: &str = include_str!("../testdata/test-key.asc");
const FPR: &str = include_str!("../testdata/test-key.fpr");

fn testdata_repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/tlnet")
}

/// A fresh root using `repo` as its repository, with the test key trusted.
fn setup(repo: &std::path::Path) -> (tempfile::TempDir, Root, Ctx) {
    let dir = tempfile::tempdir().unwrap();
    let root = Root::new(dir.path().join("root"));
    let mut ctx = Ctx::open(root.clone()).unwrap();
    ctx.set_quiet(true);
    ctx.test_key = Some((KEY, FPR));
    ctx.db.set("repository", &format!("file://{}", repo.display())).unwrap();
    (dir, root, ctx)
}

#[test]
fn refresh_then_ensure_path_installs_with_siblings() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    assert!(matches!(ctx.refresh(true).unwrap(), Freshness::Updated { to: 4242, .. }));
    assert_eq!(ctx.refresh(false).unwrap(), Freshness::Fresh);
    drop(ctx);

    let got = ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", true).unwrap().unwrap();
    let rel: Vec<String> =
        got.iter().map(|p| p.strip_prefix(&root.dir).unwrap().to_string_lossy().into_owned()).collect();
    assert_eq!(rel[0], "texmf-dist/tex/latex/foo/foo.sty");
    // Siblings: the rest of foo, and bar, installed as foo's dependency.
    assert!(rel.contains(&"texmf-dist/tex/latex/foo/foo.lua".to_string()));
    assert!(rel.contains(&"texmf-dist/tex/latex/bar/bar.sty".to_string()));
    assert!(got.iter().all(|p| p.exists()));

    let ctx = Ctx::open(root.clone()).unwrap();
    let installed = ctx.db.installed().unwrap();
    assert_eq!(installed["foo"].reason, "auto");
    assert_eq!(installed["bar"].reason, "dependency");
    assert!(!installed.contains_key("fonts-x"));
    // The first install creates ls-R by a full (sorted) scan.
    let lsr = fs::read_to_string(root.texmf_dist().join("ls-R")).unwrap();
    assert!(lsr.contains("./tex/latex/foo:\nfoo.lua\nfoo.sty\n"), "{lsr}");
    assert!(lsr.contains("./tex/latex/bar:\nbar.sty\n"));

    // Already installed: just the path, nothing else.
    let again = ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", true).unwrap().unwrap();
    assert_eq!(again.len(), 1);
    // Paths outside texmf-dist or escaping it are refused.
    assert!(ensure::ensure_path(&root, "foo", "../etc/passwd", true).unwrap().is_none());
    assert!(ensure::ensure_path(&root, "foo", "bin/universal-darwin/x", true).unwrap().is_none());
}

#[test]
fn phase0_ensure_resolves_by_name() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    drop(ctx);
    let tfm = ensure::kind("tfm").unwrap();
    let p = ensure::ensure(&root, tfm, "x10").unwrap().unwrap();
    assert!(p.ends_with("texmf-dist/fonts/tfm/public/x/x10.tfm"));
    assert!(ensure::ensure(&root, ensure::kind("tex").unwrap(), "nonexistent.cfg").unwrap().is_none());
}

#[test]
fn offline_install_fails_with_its_own_status() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    ctx.mark_offline();
    drop(ctx);
    let e = ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", false).unwrap_err();
    let why = e.downcast_ref::<ensure::NotInstalled>().expect("NotInstalled");
    assert_eq!(why.exit_code(), ensure::NotInstalled::FAILED);
    // A file nobody provides is still just "not found".
    assert!(ensure::ensure(&root, ensure::kind("tex").unwrap(), "nonexistent.cfg").unwrap().is_none());
}

#[test]
fn unreachable_pinned_mirror_fails_over() {
    let (_d, _root, mut ctx) = setup(&testdata_repo());
    let configured = ctx.repository_url().unwrap();
    // Pin a mirror that refuses connections, as if resolved earlier.
    ctx.db.set("mirror", "http://127.0.0.1:9/tlnet/").unwrap();
    ctx.db.set("mirror_for", &configured).unwrap();
    ctx.db.set("mirror_pinned_at", &now_secs().to_string()).unwrap();

    assert!(matches!(ctx.refresh(true).unwrap(), Freshness::Updated { .. }));
    assert!(ctx.db.get("bad_mirror:127.0.0.1:9").unwrap().is_some());
    assert_eq!(ctx.db.get("mirror").unwrap().as_deref(), Some(format!("{configured}/").as_str()));
    assert!(!ctx.offline().unwrap());
}

#[test]
fn corrupt_archive_is_rejected() {
    let src = testdata_repo();
    let copy = tempfile::tempdir().unwrap();
    for sub in ["tlpkg", "archive"] {
        fs::create_dir_all(copy.path().join(sub)).unwrap();
        for e in fs::read_dir(src.join(sub)).unwrap() {
            let e = e.unwrap();
            fs::copy(e.path(), copy.path().join(sub).join(e.file_name())).unwrap();
        }
    }
    let mut bar = fs::read(copy.path().join("archive/bar.tar.xz")).unwrap();
    bar.push(0); // four bytes was enough to break a real mirror; one will do
    fs::write(copy.path().join("archive/bar.tar.xz"), bar).unwrap();

    let (_d, _root, mut ctx) = setup(copy.path());
    ctx.refresh(true).unwrap();
    let err = install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap_err();
    assert!(err.chain().any(|c| c.downcast_ref::<ChecksumMismatch>().is_some()), "{err:#}");
    assert!(ctx.db.installed().unwrap().is_empty(), "nothing may be installed after a failed download");
}

#[test]
fn interrupted_install_is_redone() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    assert!(!root.journal_dir().join("foo").exists());

    // As if mtx was killed while (re)installing bar.
    fs::write(root.journal_dir().join("bar"), b"").unwrap();
    fs::remove_file(root.texmf_dist().join("tex/latex/bar/bar.sty")).unwrap();
    let r = install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    assert_eq!(r.installed.iter().map(|(n, _)| n.as_str()).collect::<Vec<_>>(), vec!["bar"]);
    assert!(root.texmf_dist().join("tex/latex/bar/bar.sty").exists());
    assert!(!root.journal_dir().join("bar").exists());
    assert_eq!(ctx.db.installed().unwrap()["bar"].reason, "dependency");
}

#[test]
fn any_install_or_lookup_finishes_an_interrupted_install() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();

    // Killed while finishing foo (recorded, but ls-R/configuration not done):
    // installing something unrelated finishes it and keeps its reason.
    fs::write(root.journal_dir().join("foo"), b"").unwrap();
    let r = install::install(&mut ctx, &["fonts-x"], Reason::Auto).unwrap();
    let names: Vec<&str> = r.installed.iter().map(|(n, _)| n.as_str()).collect();
    assert!(names.contains(&"foo") && names.contains(&"fonts-x"), "{names:?}");
    assert!(!root.journal_dir().join("foo").exists());
    assert_eq!(ctx.db.installed().unwrap()["foo"].reason, "explicit");
    drop(ctx);

    // A lookup of a file that exists, but whose package is journaled,
    // redoes the package instead of trusting it; a healthy package's file
    // is returned at once.
    fs::write(root.journal_dir().join("bar"), b"").unwrap();
    let got = ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", false).unwrap().unwrap();
    assert!(got[0].exists());
    assert!(root.journal_dir().join("bar").exists(), "foo is healthy: no install");
    let got = ensure::ensure_path(&root, "bar", "texmf-dist/tex/latex/bar/bar.sty", false).unwrap().unwrap();
    assert!(got[0].exists());
    assert!(!root.journal_dir().join("bar").exists());
}

#[test]
fn remove_respects_dependencies() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    let err = install::remove(&mut ctx, &["bar"], false).unwrap_err();
    assert!(err.to_string().contains("foo depends on bar"), "{err:#}");

    assert_eq!(install::remove(&mut ctx, &["foo"], false).unwrap(), vec!["foo"]);
    assert!(!root.texmf_dist().join("tex/latex/foo").exists(), "empty directories are removed");
    assert!(root.texmf_dist().join("tex/latex/bar/bar.sty").exists());
    let lsr = fs::read_to_string(root.texmf_dist().join("ls-R")).unwrap();
    assert!(!lsr.contains("foo.sty") && lsr.contains("bar.sty"));
    assert_eq!(install::remove(&mut ctx, &["bar"], false).unwrap(), vec!["bar"]);
    assert!(ctx.db.installed().unwrap().is_empty());
}

fn testdata(sub: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata").join(sub)
}

#[test]
fn next_release_pins_the_frozen_repository() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();

    // tlnet moves on to TeX Live 2027. The first historic mirror is down.
    ctx.db.set("repository", &format!("file://{}", testdata("tlnet-next").display())).unwrap();
    ctx.unpin_mirror().unwrap();
    let historic = format!("file://{}", testdata("historic").display());
    ctx.db.set("historic_mirrors", &format!("http://127.0.0.1:9/ {historic}")).unwrap();

    assert!(matches!(ctx.refresh(true).unwrap(), Freshness::Updated { from: Some(4242), to: 4300 }));
    assert_eq!(ctx.db.get("repository").unwrap().as_deref(), Some("historic:2026"));
    assert_eq!(ctx.db.get_u64("newer_release").unwrap(), Some(2027));
    let mirror = ctx.db.get("mirror").unwrap().unwrap();
    assert_eq!(mirror, format!("{historic}/systems/texlive/2026/tlnet-final/"));
    assert!(ctx.tlpdb().unwrap().config.frozen);

    // Installs keep working from the frozen repository, and it stays pinned.
    install::install(&mut ctx, &["fonts-x"], Reason::Explicit).unwrap();
    assert!(root.texmf_dist().join("fonts/tfm/public/x/x10.tfm").exists());
    assert_eq!(ctx.refresh(true).unwrap(), Freshness::Unchanged);
}

#[test]
fn bootstrap_from_carries_requested_and_on_demand_packages() {
    let (_d, old_root, mut old) = setup(&testdata_repo());
    old.refresh(true).unwrap();
    install::install(&mut old, &["foo"], Reason::Explicit).unwrap();
    install::install(&mut old, &["fonts-x"], Reason::Auto).unwrap();
    old.db.record("dropped-in-2027", 1, Reason::Explicit, &[]).unwrap();
    drop(old);

    let (_d2, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    let c = crate::bootstrap::carried_packages(&ctx.tlpdb().unwrap(), &old_root).unwrap();
    // bar came in as foo's dependency; foo brings it again.
    assert_eq!(c.explicit, vec!["foo"]);
    assert_eq!(c.auto, vec!["fonts-x"]);
    assert_eq!(c.unknown, vec!["dropped-in-2027"]);
    let empty = Root::new(root.dir.join("nothing-here"));
    assert!(crate::bootstrap::carried_packages(&ctx.tlpdb().unwrap(), &empty).is_err());
}

mod consent_tests {
    use std::sync::atomic::{AtomicUsize, Ordering};

    use super::*;
    use crate::consent::{Answer, Declined};

    fn auto_install(ctx: &mut Ctx, pkg: &str) -> anyhow::Result<install::Report> {
        ctx.ask_for = Some(format!("{pkg}.sty"));
        install::install(ctx, &[pkg], Reason::Auto)
    }

    #[test]
    fn autoinstall_no_declines_and_logs() {
        let (_d, root, mut ctx) = setup(&testdata_repo());
        ctx.refresh(true).unwrap();
        ctx.db.set("autoinstall", "no").unwrap();
        drop(ctx);
        let e = ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", false).unwrap_err();
        let why = e.downcast_ref::<ensure::NotInstalled>().expect("NotInstalled");
        assert_eq!(why.exit_code(), ensure::NotInstalled::DECLINED);
        assert!(!root.texmf_dist().join("tex/latex/foo/foo.sty").exists());
        let problems: Vec<_> = crate::logview::tail(&root).into_iter().filter(|e| e.is_problem()).collect();
        assert_eq!(problems.len(), 1);
        assert!(problems[0].msg.starts_with("declined: foo.sty needs package foo and 1 more"), "{}", problems[0].msg);
        // Explicit installs are not subject to the policy.
        let mut ctx = Ctx::open(root.clone()).unwrap();
        ctx.set_quiet(true);
        ctx.test_key = Some((KEY, FPR));
        install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    }

    #[test]
    fn ask_without_any_ui_uses_the_fallback() {
        let (_d, root, mut ctx) = setup(&testdata_repo());
        ctx.refresh(true).unwrap();
        ctx.db.set("autoinstall", "ask").unwrap();
        ctx.prompter = |_, _| Err("no terminal; dialog: osascript exit 1".into());
        auto_install(&mut ctx, "bar").unwrap(); // fallback defaults to yes
        // The log says why nobody was asked and where the request came from.
        let log = fs::read_to_string(root.log_path()).unwrap();
        let line = log.lines().find(|l| l.contains("could not ask about")).expect(&log);
        assert!(line.contains("(no terminal; dialog: osascript exit 1; from "), "{line}");
        assert!(line.ends_with("ask_fallback is yes"), "{line}");
        ctx.db.set("ask_fallback", "no").unwrap();
        let err = auto_install(&mut ctx, "fonts-x").unwrap_err();
        assert!(err.downcast_ref::<Declined>().is_some(), "{err:#}");
        assert!(!ctx.db.installed().unwrap().contains_key("fonts-x"));
    }

    static ASKED: AtomicUsize = AtomicUsize::new(0);

    #[test]
    fn ask_all_covers_the_rest_of_the_run() {
        let (_d, _root, mut ctx) = setup(&testdata_repo());
        ctx.refresh(true).unwrap();
        ctx.db.set("autoinstall", "ask").unwrap();
        ctx.prompter = |_, req| {
            assert!(req.describe().starts_with("foo.sty needs package foo and 1 more"), "{}", req.describe());
            // foo, with bar as the dependency it brings along.
            assert_eq!(req.items.len(), 1);
            assert_eq!(req.items[0].name, "foo");
            assert_eq!(req.items[0].deps.iter().map(|d| d.name.as_str()).collect::<Vec<_>>(), ["bar"]);
            assert!(req.question().contains("\n  foo"), "{}", req.question());
            ASKED.fetch_add(1, Ordering::SeqCst);
            Ok((Answer::All, "test"))
        };
        auto_install(&mut ctx, "foo").unwrap();
        auto_install(&mut ctx, "fonts-x").unwrap(); // not asked again
        assert_eq!(ASKED.load(Ordering::SeqCst), 1);
        let installed = ctx.db.installed().unwrap();
        assert_eq!(installed["foo"].reason, "auto");
        assert!(installed.contains_key("fonts-x"));
    }

    #[test]
    fn ask_none_declines_the_rest_of_the_run() {
        let (_d, _root, mut ctx) = setup(&testdata_repo());
        ctx.refresh(true).unwrap();
        ctx.db.set("autoinstall", "ask").unwrap();
        ctx.prompter = |_, _| Ok((Answer::None, "test"));
        assert!(auto_install(&mut ctx, "foo").is_err());
        ctx.prompter = |_, _| panic!("asked again after `none`");
        assert!(auto_install(&mut ctx, "fonts-x").is_err());
        assert!(ctx.db.installed().unwrap().is_empty());
    }
}

#[test]
fn documentation_is_installed_on_request_and_removed_with_its_package() {
    use crate::docs;
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    let manual = root.texmf_dist().join("doc/latex/foo/foo-manual.pdf");
    assert!(!manual.exists(), "runtime installs never bring documentation");

    let tlpdb = ctx.tlpdb().unwrap();
    assert_eq!(docs::packages_for(&tlpdb, "foo"), vec!["foo"]);
    assert_eq!(docs::packages_for(&tlpdb, "foo-manual"), vec!["foo"]); // by doc file name
    assert!(docs::packages_for(&tlpdb, "bar").is_empty()); // bar has no documentation

    assert_eq!(docs::install(&mut ctx, &["foo"], Reason::Auto).unwrap(), vec!["foo"]);
    assert!(manual.exists());
    assert_eq!(ctx.db.installed().unwrap()["foo.doc"].reason, "auto");
    let lsr = fs::read_to_string(root.texmf_dist().join("ls-R")).unwrap();
    assert!(lsr.contains("foo-manual.pdf"), "{lsr}");
    assert!(docs::install(&mut ctx, &["foo"], Reason::Auto).unwrap().is_empty());
    assert!(install::outdated(&ctx, &tlpdb).unwrap().is_empty());
    assert!(docs::install(&mut ctx, &["bar"], Reason::Auto).unwrap().is_empty());

    assert_eq!(install::remove(&mut ctx, &["foo"], false).unwrap(), vec!["foo", "foo.doc"]);
    assert!(!manual.exists());
}

fn synced_repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/tlnet-synced")
}

fn revision(ctx: &Ctx, pkg: &str) -> Option<u64> {
    ctx.db.installed().unwrap().get(pkg).map(|i| i.revision)
}

/// A root with bar and the kernel package latex at r7 whose repository has
/// since moved on (testdata/tlnet-synced: bar, baz, latex at r8).
fn outdated_root() -> (tempfile::TempDir, Root, Ctx) {
    let (d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["bar", "latex"], Reason::Explicit).unwrap();
    crate::config::set(&mut ctx, "repository", &format!("file://{}", synced_repo().display())).unwrap();
    assert!(matches!(ctx.refresh(true).unwrap(), Freshness::Updated { to: 4243, .. }));
    (d, root, ctx)
}

/// Decision 0018: during a compile only missing packages are installed;
/// outdated ones (a dependency, the kernel) wait, and `mtx prefetch`
/// (before the next latexmk build) upgrades them without asking.
#[test]
fn compile_defers_upgrades_until_prefetch() {
    let (_d, root, ctx) = outdated_root();
    drop(ctx);
    // foo (r7) depends on bar: bar stays at r7 during the compile.
    ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", false).unwrap().unwrap();
    let ctx = Ctx::open(root.clone()).unwrap();
    assert_eq!((revision(&ctx, "foo"), revision(&ctx, "bar")), (Some(7), Some(7)));
    assert_eq!(install::deferred(&ctx).unwrap(), ["bar"]);
    drop(ctx);
    // baz (r8) is newer than the installed kernel: the kernel waits too.
    ensure::ensure_path(&root, "baz", "texmf-dist/tex/latex/baz/baz.sty", false).unwrap().unwrap();
    let mut ctx = Ctx::open(root.clone()).unwrap();
    ctx.set_quiet(true);
    ctx.test_key = Some((KEY, FPR));
    assert_eq!(revision(&ctx, "latex"), Some(7));
    assert_eq!(install::deferred(&ctx).unwrap(), ["bar", "latex"]);
    assert!(crate::doctor::check(&ctx, "").unwrap().iter().any(|f| f.message.contains("upgrades waiting")));

    // A prompt would fail the test: catching up does not ask.
    ctx.prompter = |_, _| panic!("asked about deferred upgrades");
    ctx.ask_for = Some("doc.tex".into());
    let r = install::catch_up(&mut ctx);
    let mut got: Vec<&str> = r.installed.iter().map(|(n, _)| n.as_str()).collect();
    got.sort();
    assert_eq!(got, ["bar", "latex"]);
    assert_eq!(ctx.ask_for.as_deref(), Some("doc.tex"), "prefetch's own installs still ask");
    assert!(install::deferred(&ctx).unwrap().is_empty());
    assert!(fs::read_to_string(root.texmf_dist().join("tex/latex/bar/bar.sty")).unwrap().contains("revised"));
}

/// Outside a compile an install upgrades outdated dependencies, and the
/// kernel when the new package is newer than the installed kernel.
#[test]
fn install_upgrades_dependencies_and_the_kernel() {
    let (_d, _root, mut ctx) = outdated_root();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    assert_eq!(revision(&ctx, "bar"), Some(8), "dependency upgraded");
    assert_eq!(revision(&ctx, "latex"), Some(7), "foo (r7) is no newer than the kernel");
    install::install(&mut ctx, &["baz"], Reason::Explicit).unwrap();
    assert_eq!(revision(&ctx, "latex"), Some(8), "baz (r8) is newer than the kernel");
    assert!(install::deferred(&ctx).unwrap().is_empty());
}

/// `prefetch_depth`: by default prefetch follows `\RequirePackage` into the
/// installed foo.sty (baz); with `document` only what the document names.
#[test]
fn prefetch_depth_decides_whether_installed_files_are_read() {
    for (depth, want) in [(None, vec!["bar", "baz", "foo"]), (Some("document"), vec!["bar", "foo"])] {
        let (d, _root, mut ctx) = setup(&testdata_repo());
        ctx.refresh(true).unwrap();
        if let Some(depth) = depth {
            crate::config::set(&mut ctx, "prefetch_depth", depth).unwrap();
        }
        let doc = d.path().join("doc.tex");
        fs::write(&doc, "\\documentclass{article}\n\\usepackage{foo}\n").unwrap();
        crate::prefetch::prefetch(&mut ctx, &doc).unwrap();
        assert_eq!(installed_names(&ctx), want, "prefetch_depth {depth:?}");
    }
}

fn installed_names(ctx: &Ctx) -> Vec<String> {
    ctx.db.installed().unwrap().into_keys().collect()
}

/// `freshness_ttl 0` checks the mirror every time; the default trusts a
/// check for an hour.
#[test]
fn freshness_ttl_sets_how_long_a_check_holds() {
    let (_d, _root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    assert_eq!(ctx.refresh(false).unwrap(), Freshness::Fresh);
    crate::config::set(&mut ctx, "freshness_ttl", "0").unwrap();
    assert_eq!(ctx.refresh(false).unwrap(), Freshness::Unchanged);
}

/// `docs always`: an install outside a compile brings the documentation;
/// one during a compile does not, and `docs::missing` lists it for
/// `mtx update`.
#[test]
fn docs_always_installs_documentation_outside_compiles() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    crate::config::set(&mut ctx, "docs", "always").unwrap();
    drop(ctx);
    ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", false).unwrap().unwrap();
    let mut ctx = Ctx::open(root.clone()).unwrap();
    ctx.set_quiet(true);
    ctx.test_key = Some((KEY, FPR));
    assert!(!installed_names(&ctx).contains(&"foo.doc".to_string()), "not during a compile");
    assert_eq!(crate::docs::missing(&ctx, &ctx.tlpdb().unwrap()).unwrap(), ["foo"]);
    install::remove(&mut ctx, &["foo"], false).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    assert!(installed_names(&ctx).contains(&"foo.doc".to_string()));
    assert!(root.dir.join("texmf-dist/doc/latex/foo/foo-manual.pdf").exists());
}

/// A CTAN stand-in served over HTTP: the JSON API under `json/2.0/pkg/`
/// and TDS archives under `install/`.
struct FakeCtan {
    dir: tempfile::TempDir,
    server: crate::fault_server::FaultServer,
}

impl FakeCtan {
    fn new() -> FakeCtan {
        let dir = tempfile::tempdir().unwrap();
        let server = crate::fault_server::FaultServer::serve(dir.path().to_path_buf());
        FakeCtan { dir, server }
    }

    fn api(&self) -> String {
        format!("{}json/2.0/pkg/", self.server.base)
    }

    fn mirror(&self) -> String {
        format!("{}install/", self.server.base)
    }

    /// Publish `pkg` at `version` with a TDS zip of `files` (path, content).
    fn publish(&self, pkg: &str, version: &str, files: &[(&str, &str)]) {
        use std::io::Write;
        let api = self.dir.path().join("json/2.0/pkg");
        fs::create_dir_all(&api).unwrap();
        let zip_rel = format!("macros/latex/contrib/{pkg}.tds.zip");
        let json = format!(
            r#"{{"id":"{pkg}","version":{{"number":"{version}","date":""}},"install":"/{zip_rel}","texlive":"{pkg}"}}"#
        );
        fs::write(api.join(pkg), json).unwrap();
        let mut w = zip::ZipWriter::new(std::io::Cursor::new(Vec::new()));
        for (path, content) in files {
            w.start_file(*path, zip::write::SimpleFileOptions::default()).unwrap();
            w.write_all(content.as_bytes()).unwrap();
        }
        let zip_path = self.dir.path().join("install").join(&zip_rel);
        fs::create_dir_all(zip_path.parent().unwrap()).unwrap();
        fs::write(zip_path, w.finish().unwrap().into_inner()).unwrap();
    }
}

/// `mtx install --from-ctan`: TeX Live's package first, then CTAN's files in
/// texmf-ctan (TDS inputs only); formats see the overlay in their stamp;
/// `mtx update` drops it once tlnet has caught up.
#[test]
fn ctan_overlay_until_tlnet_catches_up() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    let ctan = FakeCtan::new();
    ctan.publish(
        "baz",
        "1.1",
        &[
            ("tex/latex/baz/baz.sty", "% baz 1.1 from CTAN"),
            ("tex/latex/baz/baz-extra.sty", "% new in 1.1"),
            ("doc/latex/baz/README", "read me"),
            ("source/latex/baz/baz.dtx", "% source"),
            ("web2c/texmf.cnf", "TEXMF = /evil"),
        ],
    );
    let fmt = crate::configfiles::Format {
        name: "x".into(),
        engine: "pdftex".into(),
        patterns: "-".into(),
        options: String::new(),
        enabled: true,
        fmttriggers: vec!["baz".into()],
    };
    let stamp = |ctx: &Ctx| crate::formats::stamp(&root, &fmt, &ctx.db.installed().unwrap());

    let got = crate::ctan::install_from(&mut ctx, &["baz"], &ctan.api(), &ctan.mirror()).unwrap();
    assert_eq!(got, [("baz".to_string(), "1.1".to_string())]);
    let tree = root.dir.join(crate::ctan::TREE);
    assert_eq!(fs::read_to_string(tree.join("tex/latex/baz/baz.sty")).unwrap(), "% baz 1.1 from CTAN");
    assert!(tree.join("doc/latex/baz/README").exists());
    assert!(!tree.join("source").exists() && !tree.join("web2c").exists(), "only TDS input trees are taken");
    assert_eq!(revision(&ctx, "baz"), Some(7), "TeX Live's package comes first");
    assert_eq!(crate::ctan::recorded(&ctx, "baz").unwrap().unwrap(), ("1.1".into(), "baz".into(), "1.0".into()));
    let with_overlay = stamp(&ctx);
    assert!(with_overlay.contains("trigger baz r7 ctan@"), "{with_overlay}");
    assert!(crate::ctan::caught_up(&ctx, &ctx.tlpdb().unwrap()).unwrap().is_empty());

    // A newer CTAN archive replaces the overlay, dropping files it no longer has.
    ctan.publish("baz", "1.2", &[("tex/latex/baz/baz.sty", "% baz 1.2")]);
    crate::ctan::install_from(&mut ctx, &["baz"], &ctan.api(), &ctan.mirror()).unwrap();
    assert!(!tree.join("tex/latex/baz/baz-extra.sty").exists());
    assert!(!tree.join("doc").exists(), "empty directories go too");

    // tlnet moves to 1.1 (behind CTAN's 1.2, but it changed): update drops it.
    crate::config::set(&mut ctx, "repository", &format!("file://{}", synced_repo().display())).unwrap();
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["baz"], Reason::Upgrade).unwrap();
    let caught = crate::ctan::caught_up(&ctx, &ctx.tlpdb().unwrap()).unwrap();
    assert_eq!(caught, [("baz".to_string(), "1.2".to_string(), "1.1".to_string())]);
    assert!(crate::ctan::drop_overlay(&mut ctx, "baz").unwrap());
    assert!(!tree.join("tex").exists());
    assert!(crate::ctan::overlays(&ctx).unwrap().is_empty());
    assert!(crate::ctan::recorded(&ctx, "baz").unwrap().is_none());
    assert!(stamp(&ctx).contains("trigger baz r8\n"));
    assert!(root.texmf_dist().join("tex/latex/baz/baz.sty").exists(), "TeX Live's version is still there");
}

/// Unsafe or useless archives are refused without placing anything; so is
/// a package CTAN has no TDS archive of.
#[test]
fn ctan_refuses_bad_archives() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    let ctan = FakeCtan::new();
    ctan.publish("baz", "1.1", &[("tex/latex/baz/baz.sty", "ok"), ("../../escape.sty", "evil")]);
    assert!(crate::ctan::install_from(&mut ctx, &["baz"], &ctan.api(), &ctan.mirror()).is_err());
    ctan.publish("baz", "1.1", &[("source/latex/baz/baz.dtx", "only sources")]);
    let e = crate::ctan::install_from(&mut ctx, &["baz"], &ctan.api(), &ctan.mirror()).unwrap_err();
    assert!(format!("{e:#}").contains("no TeX files"), "{e:#}");
    fs::write(ctan.dir.path().join("json/2.0/pkg/qux"), r#"{"id":"qux","version":{"number":"2"}}"#).unwrap();
    let e = crate::ctan::install_from(&mut ctx, &["qux"], &ctan.api(), &ctan.mirror()).unwrap_err();
    assert!(e.to_string().contains("no installable"), "{e:#}");
    assert!(!root.dir.join(crate::ctan::TREE).exists());
    assert!(crate::ctan::overlays(&ctx).unwrap().is_empty());
    assert!(fs::read_dir(&root.dir).unwrap().flatten().all(|e| !e.file_name().to_string_lossy().starts_with(".staging-ctan")));
}

/// Installs append to ls-R; `compact_lsr` (run by `mtx update`) rewrites it
/// with one block per directory and without files that are gone.
#[test]
fn update_compacts_ls_r() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["bar"], Reason::Explicit).unwrap();
    install::install(&mut ctx, &["baz"], Reason::Explicit).unwrap();
    crate::lsr::append(&root.texmf_dist(), ["tex/latex/bar/gone.sty"]).unwrap();
    let blocks = |s: &str| s.matches("\n./tex/latex/bar:\n").count();
    let before = fs::read_to_string(root.texmf_dist().join("ls-R")).unwrap();
    assert!(blocks(&before) == 2 && before.contains("gone.sty"), "{before}");
    install::compact_lsr(&ctx).unwrap();
    let after = fs::read_to_string(root.texmf_dist().join("ls-R")).unwrap();
    assert_eq!(blocks(&after), 1, "{after}");
    assert!(!after.contains("gone.sty") && after.contains("\n./tex/latex/baz:\nbaz.sty\n"));
}
