//! End-to-end tests against `testdata/tlnet`, a tiny signed repository
//! generated by `tools/make_test_repo.sh` (packages `foo` → depends on
//! `bar`, and `fonts-x`). They run offline.

use std::fs;
use std::path::PathBuf;

use crate::ctx::{Ctx, Freshness};
use crate::db::now_secs;
use crate::ensure;
use crate::install;
use crate::db::Reason;
use crate::repo::ChecksumMismatch;
use crate::root::Root;

const KEY: &str = include_str!("../testdata/test-key.asc");
const FPR: &str = include_str!("../testdata/test-key.fpr");

fn testdata_repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/tlnet")
}

/// A fresh root using `repo` as its repository, with the test key trusted.
fn setup(repo: &std::path::Path) -> (tempfile::TempDir, Root, Ctx) {
    let dir = tempfile::tempdir().unwrap();
    let root = Root::new(dir.path().join("root"));
    let mut ctx = Ctx::open(root.clone()).unwrap();
    ctx.set_quiet(true);
    ctx.test_key = Some((KEY, FPR));
    ctx.db.set("repository", &format!("file://{}", repo.display())).unwrap();
    (dir, root, ctx)
}

#[test]
fn refresh_then_ensure_path_installs_with_siblings() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    assert!(matches!(ctx.refresh(true).unwrap(), Freshness::Updated { to: 4242, .. }));
    assert_eq!(ctx.refresh(false).unwrap(), Freshness::Fresh);
    drop(ctx);

    let got = ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", true).unwrap().unwrap();
    let rel: Vec<String> =
        got.iter().map(|p| p.strip_prefix(&root.dir).unwrap().to_string_lossy().into_owned()).collect();
    assert_eq!(rel[0], "texmf-dist/tex/latex/foo/foo.sty");
    // Siblings: the rest of foo, and bar, installed as foo's dependency.
    assert!(rel.contains(&"texmf-dist/tex/latex/foo/foo.lua".to_string()));
    assert!(rel.contains(&"texmf-dist/tex/latex/bar/bar.sty".to_string()));
    assert!(got.iter().all(|p| p.exists()));

    let ctx = Ctx::open(root.clone()).unwrap();
    let installed = ctx.db.installed().unwrap();
    assert_eq!(installed["foo"].reason, "auto");
    assert_eq!(installed["bar"].reason, "dependency");
    assert!(!installed.contains_key("fonts-x"));
    // The first install creates ls-R by a full (sorted) scan.
    let lsr = fs::read_to_string(root.texmf_dist().join("ls-R")).unwrap();
    assert!(lsr.contains("./tex/latex/foo:\nfoo.lua\nfoo.sty\n"), "{lsr}");
    assert!(lsr.contains("./tex/latex/bar:\nbar.sty\n"));

    // Already installed: just the path, nothing else.
    let again = ensure::ensure_path(&root, "foo", "texmf-dist/tex/latex/foo/foo.sty", true).unwrap().unwrap();
    assert_eq!(again.len(), 1);
    // Paths outside texmf-dist or escaping it are refused.
    assert!(ensure::ensure_path(&root, "foo", "../etc/passwd", true).unwrap().is_none());
    assert!(ensure::ensure_path(&root, "foo", "bin/universal-darwin/x", true).unwrap().is_none());
}

#[test]
fn phase0_ensure_resolves_by_name() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    drop(ctx);
    let tfm = ensure::kind("tfm").unwrap();
    let p = ensure::ensure(&root, tfm, "x10").unwrap().unwrap();
    assert!(p.ends_with("texmf-dist/fonts/tfm/public/x/x10.tfm"));
    assert!(ensure::ensure(&root, ensure::kind("tex").unwrap(), "nonexistent.cfg").unwrap().is_none());
}

#[test]
fn unreachable_pinned_mirror_fails_over() {
    let (_d, _root, mut ctx) = setup(&testdata_repo());
    let configured = ctx.repository_url().unwrap();
    // Pin a mirror that refuses connections, as if resolved earlier.
    ctx.db.set("mirror", "http://127.0.0.1:9/tlnet/").unwrap();
    ctx.db.set("mirror_for", &configured).unwrap();
    ctx.db.set("mirror_pinned_at", &now_secs().to_string()).unwrap();

    assert!(matches!(ctx.refresh(true).unwrap(), Freshness::Updated { .. }));
    assert!(ctx.db.get("bad_mirror:127.0.0.1:9").unwrap().is_some());
    assert_eq!(ctx.db.get("mirror").unwrap().as_deref(), Some(format!("{configured}/").as_str()));
    assert!(!ctx.offline().unwrap());
}

#[test]
fn corrupt_archive_is_rejected() {
    let src = testdata_repo();
    let copy = tempfile::tempdir().unwrap();
    for sub in ["tlpkg", "archive"] {
        fs::create_dir_all(copy.path().join(sub)).unwrap();
        for e in fs::read_dir(src.join(sub)).unwrap() {
            let e = e.unwrap();
            fs::copy(e.path(), copy.path().join(sub).join(e.file_name())).unwrap();
        }
    }
    let mut bar = fs::read(copy.path().join("archive/bar.tar.xz")).unwrap();
    bar.push(0); // four bytes was enough to break a real mirror; one will do
    fs::write(copy.path().join("archive/bar.tar.xz"), bar).unwrap();

    let (_d, _root, mut ctx) = setup(copy.path());
    ctx.refresh(true).unwrap();
    let err = install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap_err();
    assert!(err.chain().any(|c| c.downcast_ref::<ChecksumMismatch>().is_some()), "{err:#}");
    assert!(ctx.db.installed().unwrap().is_empty(), "nothing may be installed after a failed download");
}

#[test]
fn interrupted_install_is_redone() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    assert!(!root.journal_dir().join("foo").exists());

    // As if mtx was killed while (re)installing bar.
    fs::write(root.journal_dir().join("bar"), b"").unwrap();
    fs::remove_file(root.texmf_dist().join("tex/latex/bar/bar.sty")).unwrap();
    let r = install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    assert_eq!(r.installed.iter().map(|(n, _)| n.as_str()).collect::<Vec<_>>(), vec!["bar"]);
    assert!(root.texmf_dist().join("tex/latex/bar/bar.sty").exists());
    assert!(!root.journal_dir().join("bar").exists());
    assert_eq!(ctx.db.installed().unwrap()["bar"].reason, "dependency");
}

#[test]
fn remove_respects_dependencies() {
    let (_d, root, mut ctx) = setup(&testdata_repo());
    ctx.refresh(true).unwrap();
    install::install(&mut ctx, &["foo"], Reason::Explicit).unwrap();
    let err = install::remove(&mut ctx, &["bar"], false).unwrap_err();
    assert!(err.to_string().contains("foo depends on bar"), "{err:#}");

    assert_eq!(install::remove(&mut ctx, &["foo"], false).unwrap(), vec!["foo"]);
    assert!(!root.texmf_dist().join("tex/latex/foo").exists(), "empty directories are removed");
    assert!(root.texmf_dist().join("tex/latex/bar/bar.sty").exists());
    let lsr = fs::read_to_string(root.texmf_dist().join("ls-R")).unwrap();
    assert!(!lsr.contains("foo.sty") && lsr.contains("bar.sty"));
    assert_eq!(install::remove(&mut ctx, &["bar"], false).unwrap(), vec!["bar"]);
    assert!(ctx.db.installed().unwrap().is_empty());
}
